### ISSUE TITLE
ハッカソン後にサーバーが落ちる

### ISSUE THREAD

**Issue by yuta-ike** [osushi-academy/sushi-chat#265]
## 概要
ハッカソン終了後に毎度謎にサーバーが落ちてる。
実際にはnodeのプロセスが落ちる。

forever等の自動プロセス再起動ツールの導入と、chatItemやroomの管理をオンメモリではなく永続的なDBを用いることで一応解決はできるが、それでもプロセスが落ちるのは嫌なので要調査

**Comment by Eri-0910** [comment]
メモ
7月25日の回は落ちてない？

**Comment by TOMOFUMI-KONDO** [comment]
2021/9/9の03:21に落ちていることを確認。
ログを確認すると、Postgresとのコネクション周りのエラーみたい。引き続き調査

**Comment by TOMOFUMI-KONDO** [comment]
2021-09-08T18:21:43.746Z events.js:352
      throw er; // Unhandled 'error' event
      ^

2021-09-08T18:21:43.746Z error: terminating connection due to administrator command
    at Parser.parseErrorMessage (/app/server/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/app/server/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
2021-09-08T18:21:43.747Z Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/app/server/node_modules/pg/lib/client.js:319:10)
    at Client._handleErrorMessage (/app/server/node_modules/pg/lib/client.js:330:12)
    at Connection.emit (events.js:375:28)
    at /app/server/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/app/server/node_modules/pg-protocol/dist/parser.js:40:17)
    at TLSSocket.<anonymous> (/app/server/node_modules/pg-protocol/dist/index.js:11:42)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10) {
  length: 116,
  severity: 'FATAL',
  code: '57P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '3011',
  routine: 'ProcessInterrupts'
2021-09-08T18:21:43.747Z }
2021-09-08T18:21:43.996Z Node.js[3710]: ../src/node.cc:742:void node::ResetStdio(): Assertion `!(err != 0) || (err == -1 && (*__errno_location ()) == 1)' failed.
 1: 0xa24ed0 node::Abort() [node]
 2: 0xa24f4e  [node]
 3: 0x9ef984 node::ResetStdio() [node]
 4: 0x7f5a1be0252c  [/lib64/libc.so.6]
 5: 0x7f5a1be0257a  [/lib64/libc.so.6]
 6: 0x988b6c  [node]
 7: 0x9c67b3 node::Environment::Exit(int) [node]
 8: 0xa2683a node::errors::TriggerUncaughtException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>, bool) [node]
 9: 0xa26dc0 node::errors::PerIsolateMessageListener(v8::Local<v8::Message>, v8::Local<v8::Value>) [node]
2021-09-08T18:21:43.996Z 10: 0xd084b5 v8::internal::MessageHandler::ReportMessageNoExceptions(v8::internal::Isolate*, v8::internal::MessageLocation const*, v8::internal::Handle<v8::internal::Object>, v8::Local<v8::Value>) [node]
2021-09-08T18:21:43.996Z 11: 0xd0870a v8::internal::MessageHandler::ReportMessage(v8::internal::Isolate*, v8::internal::MessageLocation const*, v8::internal::Handle<v8::internal::JSMessageObject>) [node]
2021-09-08T18:21:43.996Z 12: 0xcfb62e v8::internal::Isolate::ReportPendingMessages() [node]
2021-09-08T18:21:43.996Z 13: 0xce56d0  [node]
2021-09-08T18:21:43.996Z 14: 0xce608f v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [node]
2021-09-08T18:21:43.996Z 15: 0xbacf74 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [node]
2021-09-08T18:21:43.996Z 16: 0x9853b7 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [node]
2021-09-08T18:21:43.996Z 17: 0x9930c9 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [node]
2021-09-08T18:21:43.996Z 18: 0xaf0178  [node]
2021-09-08T18:21:43.996Z 19: 0xaf3266 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [node]
2021-09-08T18:21:43.996Z 20: 0xb6e451 node::TLSWrap::ClearOut() [node]
2021-09-08T18:21:43.996Z 21: 0xb6f040 node::TLSWrap::OnStreamRead(long, uv_buf_t const&) [node]
2021-09-08T18:21:43.996Z 22: 0xafd058 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [node]
2021-09-08T18:21:43.996Z 23: 0x13ac9b7  [node]
2021-09-08T18:21:43.996Z 24: 0x13ad370  [node]
2021-09-08T18:21:43.996Z 25: 0x13b3e55  [node]
2021-09-08T18:21:43.996Z 26: 0x13a19f8 uv_run [node]
2021-09-08T18:21:43.996Z 27: 0xa65504 node::NodeMainInstance::Run() [node]
2021-09-08T18:21:43.996Z 28: 0x9f3745 node::Start(int, char**) [node]
2021-09-08T18:21:43.996Z 29: 0x7f5a1bded0ba __libc_start_main [/lib64/libc.so.6]
2021-09-08T18:21:48.832Z 30: 0x98293c  [node]

**Comment by TOMOFUMI-KONDO** [comment]
今回はPostgres周りのエラー出てたけど、前落ちた時はログ何も残ってなかったのが気になる。
もしかしたら違う原因？？
